
name: Build Deb Package

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  release:
    types: ["published"]
jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: chmod 555 homeassistant-supervised/DEBIAN/p*
      - run: dpkg-deb --build --root-owner-group homeassistant-supervised
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: homeassistant-supervised.deb